version: '3.8'

services:
  # --- Service 1: Database (PostgreSQL) ---
  db:
    image: postgres:15
    container_name: tbf_database
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpass1234
      POSTGRES_DB: tbf_system
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  # --- Service 2: Backend (Node API) ---


  backend:
    build: ./backend
    container_name: tbf_backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=adminpass1234
      - POSTGRES_DB=tbf_system
      - POSTGRES_HOST=db

  # --- Service 3: Frontend (React) ---
  frontend:
    build: ./frontend
    container_name: tbf_frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      # Syncs frontend code edits instantly
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data: